version: '3'

services:

    osrm_service:
        image: wastelabs/osrm-base-image:0.1.0
        environment:
        - OSRM_PBF_URL=https://download.openstreetmap.fr/extracts/asia/singapore.osm.pbf
        - OSRM_GRAPH_PROFILE_URL=https://raw.githubusercontent.com/WasteLabs/osrm_profiles/master/truck_v1.lua
        - OSRM_MAX_MATCHING_SIZE=86400
        ports:
        - 5000:5000