name: OSRM service testing...

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
  
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Building OSRM image
      run: bash -c "source docker/build_image.sh"

    - name: Starting docker container
      run: bash -c "docker-compose -f docker/docker-compose.yaml up -d"

    - name: Sleeping until pbf will be downloaded and parsed
      run: bash -c "sleep 60"

    - name: Sleeping until pbf will be downloaded and parsed
      run: bash -c "source docker/check_if_container_is_running.sh"

    - name: Starting docker container
      run: bash -c "docker-compose -f docker/docker-compose.yaml down"
