name: OSRM service testing...

on:
  pull_request:
    branches: [ main ]

jobs:

  terraform-deploy:

    name: "Terraform test deployment"
    runs-on: ubuntu-latest

    steps:
      #
      - name: "Setup - Checkout"
        uses: actions/checkout@v2.1.0

      - name: "Setup - Build AWS Credentials"
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
      
      - name: Terraform Init
        uses: hashicorp/terraform-github-actions/init@v0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: 'terraform'
          # AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          # AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # docker-build:

  #   runs-on: ubuntu-latest
  #   steps:

  #   - uses: actions/checkout@v2
  
  #   - name: Set up Python 3.9
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.9

  #   - name: Building OSRM docker image
  #     run: bash -c "source docker/build.sh"

  #   - name: Starting docker container
  #     run: bash -c "docker-compose -f docker/docker-compose-test.yaml up -d"

  #   - name: Sleeping until pbf will be downloaded and parsed
  #     run: bash -c "sleep 60"

  #   - name: Checking if container is running
  #     run: bash -c "source docker/check_if_container_is_running.sh"

  #   - name: Starting docker container
  #     run: bash -c "docker-compose -f docker/docker-compose-test.yaml down"
